export { AddHotel } from './AddHotel.tsx'
export { Home } from './Home.tsx'
export { Register } from './Register.tsx'
export { Login } from './Login.tsx'
export { MyHotels } from './MyHotels.tsx'
export { HotelDetails } from './HotelDetails'
export { EditHotel } from './EditHotel.tsx'
export { Search } from './Search.tsx'