export { default as authRouter } from './auth'
export { default as myHotelsRouter } from './my-hotels'
export { default as hotelsRouter  } from './hotels'
export { default as usersRouter } from './users'
export { default as bookingsRouter } from './booking'
